services:
  auth:
    build:
      dockerfile: ./docker/auth.Dockerfile
    ports:
      - "9998:9998"
  auth-ext:
    build:
      dockerfile: ./docker/auth-ext.Dockerfile
    environment:
      BACKEND_HOST: auth-ext
      OIDC_CLIENT_ID: web
      OIDC_CLIENT_SECRET: secret
      OIDC_ISSUER: http://auth:9998/
    ports:
      - "5000:5000"
  frontend:
    build:
      dockerfile: ./docker/frontend.Dockerfile
    environment:
      OIDC_CLIENT_ID: web
      OIDC_ISSUER: http://localhost:9998/
      OIDC_RESPONSE_TYPE: code
      OIDC_SCOPE: openid profile
    ports:
      - "5173:80"
  gallery:
    build:
      dockerfile: ./docker/gallery.Dockerfile
    ports:
      - "8081:8081"

  minio:
    image: minio/minio:RELEASE.2023-10-14T05-17-22Z
    command: server --address :9000 --console-address :9001 --compat /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: mona_value_abc124
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  storage:
    build:
      dockerfile: ./docker/storage.Dockerfile
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_URL: http://minio:9000
      MINIO_USERNAME: minio
      MINIO_PASSWORD: mona_value_abc124
    ports:
      - "8082:8082"
volumes:
  minio_data: {}
